// Sample data for development - in a real app, this would come from an API or CMS

export const featuredFighter = {
  id: 1,
  name: 'Rodtang Jitmuangnon',
  slug: 'rodtang-jitmuangnon',
  image: '/images/placeholder.jpg',
  record: '270-42-10 (61 KOs)',
  bio: "Known as 'The Iron Man', Rodtang is the current ONE Flyweight Muay Thai World Champion and is famous for his aggressive fighting style and iron chin.",
  country: 'Thailand',
  gym: 'Jitmuangnon Gym',
  weight: 'Flyweight',
  birthdate: '1997-07-10',
  achievements: [
    'ONE Flyweight Muay Thai World Champion',
    'Former Omnoi Stadium Champion',
  ],
};

export const topStories = [
  {
    id: 1,
    title: 'Rodtang Defeats Superlek in Epic Showdown',
    slug: 'rodtang-defeats-superlek',
    excerpt: 'In what many are calling the fight of the year, Rodtang edged out a split decision victory over Superlek at ONE Championship\'s latest event.',
    image: '/images/placeholder.jpg',
    date: 'March 1, 2025',
    category: 'Event Coverage',
    author: 'John Smith',
    content: '<!-- Full article content would go here -->',
  },
  {
    id: 2,
    title: 'Top 5 Muay Thai Camps in Thailand',
    slug: 'top-muay-thai-camps',
    excerpt: 'Looking to train in Thailand? We explore the top Muay Thai camps that offer authentic training experiences for fighters of all levels.',
    image: '/images/placeholder.jpg',
    date: 'February 25, 2025',
    category: 'Training',
    author: 'Jane Doe',
    content: '<!-- Full article content would go here -->',
  },
  {
    id: 3,
    title: 'The Evolution of Muay Thai Clinch Techniques',
    slug: 'muay-thai-clinch-evolution',
    excerpt: 'How clinch techniques have evolved over the decades and why they remain crucial to success in modern Muay Thai competition.',
    image: '/images/placeholder.jpg',
    date: 'February 20, 2025',
    category: 'Technique',
    author: 'Mike Thompson',
    content: '<!-- Full article content would go here -->',
  },
];

export const upcomingEvents = [
  {
    id: 1,
    title: 'ONE Championship: Eternal Glory',
    slug: 'one-championship-eternal-glory',
    date: 'March 15, 2025',
    venue: 'Impact Arena, Bangkok',
    image: '/images/placeholder.jpg',
    promotion: 'ONE Championship',
    description: 'ONE Championship returns to Bangkok with an action-packed card featuring the best Muay Thai fighters in the world.',
    bouts: [
      {
        fighter1: {
          name: 'Superlek',
          record: '128-29-2',
        },
        fighter2: {
          name: 'Jonathan Haggerty',
          record: '26-4-0',
        },
        weight_class: 'Flyweight',
        is_title_fight: true,
        is_main_event: true,
      },
      {
        fighter1: {
          name: 'Nong-O Gaiyanghadao',
          record: '262-54-10',
        },
        fighter2: {
          name: 'Alaverdi Ramazanov',
          record: '61-5-0',
        },
        weight_class: 'Bantamweight',
        is_title_fight: false,
        is_main_event: false,
      },
    ],
  },
  {
    id: 2,
    title: 'Lion Fight 77',
    slug: 'lion-fight-77',
    date: 'March 25, 2025',
    venue: 'Las Vegas, NV',
    image: '/images/placeholder.jpg',
    promotion: 'Lion Fight',
    description: 'Lion Fight returns to Las Vegas with an exciting card featuring top American and international Muay Thai talent.',
    bouts: [],
  },
  {
    id: 3,
    title: 'Glory Muay Thai Series',
    slug: 'glory-muay-thai-series',
    date: 'April 2, 2025',
    venue: 'Amsterdam, Netherlands',
    image: '/images/placeholder.jpg',
    promotion: 'Glory',
    description: 'Glory launches its new Muay Thai series with a stacked card in the fighting capital of Europe.',
    bouts: [],
  },
];

export const featuredVideo = {
  id: 1,
  title: 'Muay Thai Knee Striking Techniques with Buakaw',
  slug: 'muay-thai-knee-striking-buakaw',
  thumbnail: '/images/placeholder.jpg',
  url: 'https://www.youtube.com/watch?v=example',
  videoId: 'example',
  platform: 'youtube',
  duration: '15:24',
  date: 'February 15, 2025',
  category: 'Technique Breakdown',
  description: 'Legendary fighter Buakaw Banchamek demonstrates the proper technique for executing devastating knee strikes in Muay Thai.',
};

export const latestPodcast = {
  id: 1,
  title: 'Interview with Saenchai',
  slug: 'interview-with-saenchai',
  image: '/images/placeholder.jpg',
  playUrl: '#',
  shareUrl: '#',
  downloadUrl: '#',
  embedUrl: 'https://open.spotify.com/embed/episode/example',
  platform: 'spotify',
  episode: 42,
  duration: '45 minutes',
  date: 'Feb 10, 2025',
  description: 'We sit down with Muay Thai legend Saenchai to discuss his career, training philosophy, and future plans.',
  hosts: ['John Smith', 'Jane Doe'],
  guests: ['Saenchai'],
};

export const allFighters = [
  featuredFighter,
  {
    id: 2,
    name: 'Superlek Kiatmoo9',
    slug: 'superlek-kiatmoo9',
    image: '/images/placeholder.jpg',
    record: '128-29-2 (42 KOs)',
    bio: "Known as 'The Kicking Machine', Superlek is renowned for his technical excellence and devastating kicks.",
    country: 'Thailand',
    gym: 'Kiatmoo9 Gym',
    weight: 'Flyweight',
  },
  {
    id: 3,
    name: 'Jonathan Haggerty',
    slug: 'jonathan-haggerty',
    image: '/images/placeholder.jpg',
    record: '26-4-0 (8 KOs)',
    bio: "The 'General' is a British Muay Thai fighter known for his technical style and exciting performances.",
    country: 'United Kingdom',
    gym: 'Team Haggerty',
    weight: 'Bantamweight',
  },
  {
    id: 4,
    name: 'Tawanchai PK.Saenchai',
    slug: 'tawanchai-pk-saenchai',
    image: '/images/placeholder.jpg',
    record: '128-31-0 (40 KOs)',
    bio: "One of the most technically gifted fighters of his generation, Tawanchai is known for his precision striking.",
    country: 'Thailand',
    gym: 'PK.Saenchai Muaythaigym',
    weight: 'Featherweight',
  },
  {
    id: 5,
    name: 'Anissa Meksen',
    slug: 'anissa-meksen',
    image: '/images/placeholder.jpg',
    record: '103-5-0 (33 KOs)',
    bio: "Widely considered one of the best female strikers in the world, Meksen is a multiple-time world champion.",
    country: 'France',
    gym: 'Mahmoudi Gym',
    weight: "Women's Atomweight",
  },
  {
    id: 6,
    name: 'Nong-O Gaiyanghadao',
    slug: 'nong-o-gaiyanghadao',
    image: '/images/placeholder.jpg',
    record: '262-54-10 (82 KOs)',
    bio: "A living legend of Muay Thai, Nong-O is considered one of the most technically perfect fighters in the sport's history.",
    country: 'Thailand',
    gym: 'Evolve MMA',
    weight: 'Bantamweight',
  },
];

export const allVideos = [
  featuredVideo,
  {
    id: 2,
    title: 'Teep (Push Kick) Defense Strategies',
    slug: 'teep-defense-strategies',
    thumbnail: '/images/placeholder.jpg',
    url: 'https://www.youtube.com/watch?v=example2',
    videoId: 'example2',
    platform: 'youtube',
    duration: '12:37',
    date: 'February 8, 2025',
    category: 'Technique Breakdown',
  },
  {
    id: 3,
    title: 'Inside Evolve MMA: Tour with Nong-O',
    slug: 'evolve-mma-tour',
    thumbnail: '/images/placeholder.jpg',
    url: 'https://www.youtube.com/watch?v=example3',
    videoId: 'example3',
    platform: 'youtube',
    duration: '18:05',
    date: 'February 1, 2025',
    category: 'Behind The Scenes',
  },
  {
    id: 4,
    title: 'ONE Championship Fight Week Vlog',
    slug: 'one-championship-fight-week',
    thumbnail: '/images/placeholder.jpg',
    url: 'https://www.youtube.com/watch?v=example4',
    videoId: 'example4',
    platform: 'youtube',
    duration: '22:14',
    date: 'January 25, 2025',
    category: 'Behind The Scenes',
  },
  {
    id: 5,
    title: 'Interview with Liam Harrison',
    slug: 'liam-harrison-interview',
    thumbnail: '/images/placeholder.jpg',
    url: 'https://www.youtube.com/watch?v=example5',
    videoId: 'example5',
    platform: 'youtube',
    duration: '28:43',
    date: 'January 18, 2025',
    category: 'Fighter Interview',
  },
  {
    id: 6,
    title: 'Top 5 Muay Thai Combinations for Beginners',
    slug: 'muay-thai-combinations-beginners',
    thumbnail: '/images/placeholder.jpg',
    url: 'https://www.youtube.com/watch?v=example6',
    videoId: 'example6',
    platform: 'youtube',
    duration: '14:22',
    date: 'January 10, 2025',
    category: 'Technique Breakdown',
  },
];

export const allPodcasts = [
  latestPodcast,
  {
    id: 2,
    title: 'The Future of Muay Thai in the West',
    slug: 'future-of-muay-thai-west',
    image: '/images/placeholder.jpg',
    playUrl: '#',
    shareUrl: '#',
    downloadUrl: '#',
    embedUrl: 'https://open.spotify.com/embed/episode/example2',
    platform: 'spotify',
    episode: 41,
    duration: '52 minutes',
    date: 'Feb 3, 2025',
    description: 'A discussion on the growing popularity of Muay Thai in Western countries and what it means for the sport.',
    hosts: ['John Smith', 'Jane Doe'],
    guests: ['Liam Harrison', 'Kevin Ross'],
  },
  {
    id: 3,
    title: 'Training Muay Thai in Thailand vs. The West',
    slug: 'training-thailand-vs-west',
    image: '/images/placeholder.jpg',
    playUrl: '#',
    shareUrl: '#',
    downloadUrl: '#',
    embedUrl: 'https://open.spotify.com/embed/episode/example3',
    platform: 'spotify',
    episode: 40,
    duration: '48 minutes',
    date: 'Jan 27, 2025',
    description: 'Exploring the differences between training Muay Thai in Thailand versus Western countries.',
    hosts: ['John Smith', 'Jane Doe'],
    guests: ['John Wayne Parr'],
  },
];

export const shopProducts = [
  {
    id: 1,
    name: 'Nak Muay Media T-Shirt',
    slug: 'nak-muay-media-tshirt',
    image: '/images/placeholder.jpg',
    price: 29.99,
    category: 'Apparel',
    description: 'Show your love for Muay Thai with our premium Nak Muay Media t-shirt.',
    variants: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Red'],
    inStock: true,
  },
  {
    id: 2,
    name: 'Muay Thai Technique Poster',
    slug: 'muay-thai-technique-poster',
    image: '/images/placeholder.jpg',
    price: 19.99,
    category: 'Posters',
    description: 'A beautiful poster showcasing the 8 weapons of Muay Thai with detailed illustrations.',
    variants: ['18"x24"', '24"x36"'],
    colors: [],
    inStock: true,
  },
]; 